/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all recipes
         * @description Returns a summary list of all available bread recipes.
         */
        get: operations["listRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a recipe by ID
         * @description Returns the full details of a single bread recipe.
         */
        get: operations["getRecipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecipeSummary: {
            /**
             * @description Unique identifier for the recipe
             * @example sourdough-boule
             */
            id: string;
            /**
             * @description Display name of the bread recipe
             * @example Classic Sourdough Boule
             */
            name: string;
            /**
             * @description Short one-line description of the recipe
             * @example A tangy, chewy sourdough loaf with a crisp crust
             */
            summary: string;
            /**
             * Format: uri-reference
             * @description URI reference (absolute or relative) of the recipe photo
             * @example /images/sourdough-boule.jpg
             */
            photo_url: string;
        };
        Recipe: components["schemas"]["RecipeSummary"] & {
            /**
             * @description Full description of the recipe and its characteristics
             * @example A traditional sourdough boule with a complex flavour developed over a long cold fermentation. The crust is deeply caramelised and the crumb is open and chewy.
             */
            description: string;
            /** @description List of ingredients with quantities */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Ordered list of preparation steps */
            instructions: components["schemas"]["Instruction"][];
        };
        Ingredient: {
            /**
             * @description Amount of the ingredient
             * @example 500
             */
            quantity: number;
            /**
             * @description Unit of measurement (e.g. g, ml, tsp)
             * @example g
             */
            unit: string;
            /**
             * @description Name of the ingredient
             * @example strong white bread flour
             */
            name: string;
        };
        Instruction: {
            /**
             * @description Step number (1-based)
             * @example 1
             */
            step: number;
            /**
             * @description Description of what to do in this step
             * @example Mix the flour and water together and leave to autolyse for 30 minutes.
             */
            description: string;
        };
        RecipeList: {
            recipes: components["schemas"]["RecipeSummary"][];
        };
        Error: {
            /**
             * @description HTTP status code
             * @example 404
             */
            code: number;
            /**
             * @description Human-readable error message
             * @example Recipe not found
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRecipes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of bread recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeList"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the recipe */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single bread recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
