version: "2"  # requires golangci-lint >= v2.0.0

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
  exclusions:
    paths:
      - internal/gen

formatters:
  enable:
    - gofmt
    - goimports
