name: Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/wc-build-and-test.yml

  pact:
    needs: build-and-test
    uses: ./.github/workflows/wc-pact.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
