name: Deploy

on:
  workflow_call:
    secrets:
      RAILWAY_TOKEN:
        required: true
      RAILWAY_PROJECT_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Deploy API to Railway (production)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE: '@vue-pact-go-rest/api'
        working-directory: apps/api
        run: |
          npm install --global @railway/cli
          railway up --service "${RAILWAY_SERVICE}" --detach

      - uses: pnpm/action-setup@v4.4.0

      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm --filter frontend build-only

      - name: Deploy frontend to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          pnpm exec netlify deploy \
            --dir apps/frontend/dist \
            --prod \
            --message "main (${{ github.sha }})"
