name: Deploy

on:
  workflow_call:
    secrets:
      RAILWAY_API_TOKEN:
        required: true
      RAILWAY_PROJECT_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true

env:
  RAILWAY_SERVICE: '@vue-pact-go-rest/api'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Railway CLI
        run: npm install --global @railway/cli

      - name: Link to Railway environment and service
        run: |
          set -ux

          railway link \
            --project "${RAILWAY_PROJECT_ID}" \
            --environment production \
            --service "${RAILWAY_SERVICE}"

      - name: Get Railway URL
        id: get-api-url
        run: |
          set -ux

          API_URL=$(railway domain --json | jq -r '.domains[0]')
          echo "api_url=${API_URL}" >> "${GITHUB_OUTPUT}"

      - uses: pnpm/action-setup@v4.4.0

      - uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        env:
          VITE_API_BASE_URL: ${{ steps.get-api-url.outputs.api_url }}
        run: |
          set -ux

          export VITE_API_BASE_URL
          pnpm --filter frontend build-only

      - name: Deploy frontend to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          set -ux

          pnpm exec netlify deploy \
            --filter @vue-pact-go-rest/frontend \
            --dir apps/frontend/dist \
            --context production \
            --prod \
            --message "main (${{ github.sha }})"

          pnpm exec netlify \
            VITE_API_BASE_URL "${VITE_API_BASE_URL}" \
            --filter @vue-pact-go-rest/frontend \
            --context production \
            env:set
